version: "2.1"
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
  server:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
  rabbit_queue:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
